name: "Run Python application"

on: 
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 coverage
      - name: Lint with flake8
        run: flake8 --count ./statistics.py
      - name: Test with unittest
        run: coverage run -m unittest
      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v3
